// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoggerPushRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggerPushRequest) Reset()         { *m = LoggerPushRequest{} }
func (m *LoggerPushRequest) String() string { return proto.CompactTextString(m) }
func (*LoggerPushRequest) ProtoMessage()    {}
func (*LoggerPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{0}
}

func (m *LoggerPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggerPushRequest.Unmarshal(m, b)
}
func (m *LoggerPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggerPushRequest.Marshal(b, m, deterministic)
}
func (m *LoggerPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggerPushRequest.Merge(m, src)
}
func (m *LoggerPushRequest) XXX_Size() int {
	return xxx_messageInfo_LoggerPushRequest.Size(m)
}
func (m *LoggerPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggerPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoggerPushRequest proto.InternalMessageInfo

func (m *LoggerPushRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LoggerPushRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *LoggerPushRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *LoggerPushRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type LoggerPushResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggerPushResponse) Reset()         { *m = LoggerPushResponse{} }
func (m *LoggerPushResponse) String() string { return proto.CompactTextString(m) }
func (*LoggerPushResponse) ProtoMessage()    {}
func (*LoggerPushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{1}
}

func (m *LoggerPushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggerPushResponse.Unmarshal(m, b)
}
func (m *LoggerPushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggerPushResponse.Marshal(b, m, deterministic)
}
func (m *LoggerPushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggerPushResponse.Merge(m, src)
}
func (m *LoggerPushResponse) XXX_Size() int {
	return xxx_messageInfo_LoggerPushResponse.Size(m)
}
func (m *LoggerPushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggerPushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoggerPushResponse proto.InternalMessageInfo

func (m *LoggerPushResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*LoggerPushRequest)(nil), "proto.LoggerPushRequest")
	proto.RegisterType((*LoggerPushResponse)(nil), "proto.LoggerPushResponse")
}

func init() {
	proto.RegisterFile("logger.proto", fileDescriptor_d43b7bfc6b6f7b16)
}

var fileDescriptor_d43b7bfc6b6f7b16 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xc9, 0x4f, 0x4f,
	0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x99, 0x5c, 0x82,
	0x3e, 0x60, 0xe1, 0x80, 0xd2, 0xe2, 0x8c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21,
	0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x2c,
	0x96, 0x99, 0x9b, 0x2a, 0xc1, 0x04, 0x15, 0xcb, 0xcc, 0x05, 0x8b, 0x15, 0x24, 0x96, 0x64, 0x48,
	0x30, 0x43, 0xc4, 0x40, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12,
	0x09, 0x16, 0xb0, 0x30, 0x8c, 0xab, 0xa4, 0xc2, 0x25, 0x84, 0x6c, 0x55, 0x71, 0x41, 0x7e, 0x5e,
	0x71, 0xaa, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x0a, 0xd4, 0x26, 0xa6, 0xcc, 0x14, 0x23, 0x77, 0x2e,
	0x36, 0x88, 0x2a, 0x21, 0x5b, 0x2e, 0x16, 0x90, 0x4a, 0x21, 0x09, 0x88, 0x8b, 0xf5, 0x30, 0xdc,
	0x29, 0x25, 0x89, 0x45, 0x06, 0x62, 0xac, 0x12, 0x43, 0x12, 0x1b, 0x58, 0xce, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xb0, 0x1a, 0x78, 0x1e, 0xf7, 0x00, 0x00, 0x00,
}
