// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usersOrders.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UsersOrders service

type UsersOrdersService interface {
	Order(ctx context.Context, in *UsersOrdersReq, opts ...client.CallOption) (*UsersOrdersRsp, error)
}

type usersOrdersService struct {
	c    client.Client
	name string
}

func NewUsersOrdersService(name string, c client.Client) UsersOrdersService {
	return &usersOrdersService{
		c:    c,
		name: name,
	}
}

func (c *usersOrdersService) Order(ctx context.Context, in *UsersOrdersReq, opts ...client.CallOption) (*UsersOrdersRsp, error) {
	req := c.c.NewRequest(c.name, "UsersOrders.Order", in)
	out := new(UsersOrdersRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UsersOrders service

type UsersOrdersHandler interface {
	Order(context.Context, *UsersOrdersReq, *UsersOrdersRsp) error
}

func RegisterUsersOrdersHandler(s server.Server, hdlr UsersOrdersHandler, opts ...server.HandlerOption) error {
	type usersOrders interface {
		Order(ctx context.Context, in *UsersOrdersReq, out *UsersOrdersRsp) error
	}
	type UsersOrders struct {
		usersOrders
	}
	h := &usersOrdersHandler{hdlr}
	return s.Handle(s.NewHandler(&UsersOrders{h}, opts...))
}

type usersOrdersHandler struct {
	UsersOrdersHandler
}

func (h *usersOrdersHandler) Order(ctx context.Context, in *UsersOrdersReq, out *UsersOrdersRsp) error {
	return h.UsersOrdersHandler.Order(ctx, in, out)
}
