// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usersOrders.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsersOrdersGoods struct {
	GoodsId              uint64   `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsPiece           uint64   `protobuf:"varint,2,opt,name=goodsPiece,proto3" json:"goodsPiece,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersOrdersGoods) Reset()         { *m = UsersOrdersGoods{} }
func (m *UsersOrdersGoods) String() string { return proto.CompactTextString(m) }
func (*UsersOrdersGoods) ProtoMessage()    {}
func (*UsersOrdersGoods) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b08f68fbf2e14fa, []int{0}
}

func (m *UsersOrdersGoods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersOrdersGoods.Unmarshal(m, b)
}
func (m *UsersOrdersGoods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersOrdersGoods.Marshal(b, m, deterministic)
}
func (m *UsersOrdersGoods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersOrdersGoods.Merge(m, src)
}
func (m *UsersOrdersGoods) XXX_Size() int {
	return xxx_messageInfo_UsersOrdersGoods.Size(m)
}
func (m *UsersOrdersGoods) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersOrdersGoods.DiscardUnknown(m)
}

var xxx_messageInfo_UsersOrdersGoods proto.InternalMessageInfo

func (m *UsersOrdersGoods) GetGoodsId() uint64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *UsersOrdersGoods) GetGoodsPiece() uint64 {
	if m != nil {
		return m.GoodsPiece
	}
	return 0
}

type UsersOrdersReq struct {
	UserId               uint64              `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PlatformOrderNo      uint64              `protobuf:"varint,2,opt,name=platformOrderNo,proto3" json:"platformOrderNo,omitempty"`
	ShopCode             string              `protobuf:"bytes,3,opt,name=shopCode,proto3" json:"shopCode,omitempty"`
	ClientToken          string              `protobuf:"bytes,4,opt,name=clientToken,proto3" json:"clientToken,omitempty"`
	Goods                []*UsersOrdersGoods `protobuf:"bytes,5,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UsersOrdersReq) Reset()         { *m = UsersOrdersReq{} }
func (m *UsersOrdersReq) String() string { return proto.CompactTextString(m) }
func (*UsersOrdersReq) ProtoMessage()    {}
func (*UsersOrdersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b08f68fbf2e14fa, []int{1}
}

func (m *UsersOrdersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersOrdersReq.Unmarshal(m, b)
}
func (m *UsersOrdersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersOrdersReq.Marshal(b, m, deterministic)
}
func (m *UsersOrdersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersOrdersReq.Merge(m, src)
}
func (m *UsersOrdersReq) XXX_Size() int {
	return xxx_messageInfo_UsersOrdersReq.Size(m)
}
func (m *UsersOrdersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersOrdersReq.DiscardUnknown(m)
}

var xxx_messageInfo_UsersOrdersReq proto.InternalMessageInfo

func (m *UsersOrdersReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UsersOrdersReq) GetPlatformOrderNo() uint64 {
	if m != nil {
		return m.PlatformOrderNo
	}
	return 0
}

func (m *UsersOrdersReq) GetShopCode() string {
	if m != nil {
		return m.ShopCode
	}
	return ""
}

func (m *UsersOrdersReq) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

func (m *UsersOrdersReq) GetGoods() []*UsersOrdersGoods {
	if m != nil {
		return m.Goods
	}
	return nil
}

type UsersOrdersRsp struct {
	Code                 uint64   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlatformOrderNo      uint64   `protobuf:"varint,3,opt,name=platformOrderNo,proto3" json:"platformOrderNo,omitempty"`
	TotalExportPrice     float64  `protobuf:"fixed64,4,opt,name=totalExportPrice,proto3" json:"totalExportPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersOrdersRsp) Reset()         { *m = UsersOrdersRsp{} }
func (m *UsersOrdersRsp) String() string { return proto.CompactTextString(m) }
func (*UsersOrdersRsp) ProtoMessage()    {}
func (*UsersOrdersRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b08f68fbf2e14fa, []int{2}
}

func (m *UsersOrdersRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersOrdersRsp.Unmarshal(m, b)
}
func (m *UsersOrdersRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersOrdersRsp.Marshal(b, m, deterministic)
}
func (m *UsersOrdersRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersOrdersRsp.Merge(m, src)
}
func (m *UsersOrdersRsp) XXX_Size() int {
	return xxx_messageInfo_UsersOrdersRsp.Size(m)
}
func (m *UsersOrdersRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersOrdersRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UsersOrdersRsp proto.InternalMessageInfo

func (m *UsersOrdersRsp) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UsersOrdersRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UsersOrdersRsp) GetPlatformOrderNo() uint64 {
	if m != nil {
		return m.PlatformOrderNo
	}
	return 0
}

func (m *UsersOrdersRsp) GetTotalExportPrice() float64 {
	if m != nil {
		return m.TotalExportPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*UsersOrdersGoods)(nil), "proto.UsersOrdersGoods")
	proto.RegisterType((*UsersOrdersReq)(nil), "proto.UsersOrdersReq")
	proto.RegisterType((*UsersOrdersRsp)(nil), "proto.UsersOrdersRsp")
}

func init() {
	proto.RegisterFile("usersOrders.proto", fileDescriptor_3b08f68fbf2e14fa)
}

var fileDescriptor_3b08f68fbf2e14fa = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xd1, 0x4a, 0xf3, 0x40,
	0x10, 0x85, 0xff, 0xfc, 0x49, 0xaa, 0x9d, 0x80, 0xd6, 0x01, 0x75, 0xe9, 0x85, 0x84, 0x5c, 0x05,
	0xc1, 0x5e, 0xd4, 0x0b, 0x1f, 0x40, 0x54, 0x04, 0xd1, 0xb2, 0xe8, 0x03, 0xc4, 0x64, 0xac, 0xc1,
	0xb4, 0xb3, 0xdd, 0x5d, 0xc1, 0x07, 0xf1, 0x7d, 0x7c, 0x35, 0xc9, 0xa6, 0xad, 0x21, 0xcd, 0xd5,
	0x9e, 0x73, 0x66, 0x99, 0x99, 0x6f, 0xe0, 0xe8, 0xd3, 0x90, 0x36, 0x4f, 0xba, 0x20, 0x6d, 0x26,
	0x4a, 0xb3, 0x65, 0x0c, 0xdd, 0x93, 0x3c, 0xc0, 0xe8, 0xe5, 0xaf, 0x76, 0xc7, 0x5c, 0x18, 0x14,
	0xb0, 0x37, 0xaf, 0xc5, 0x7d, 0x21, 0xbc, 0xd8, 0x4b, 0x03, 0xb9, 0xb1, 0x78, 0x06, 0xe0, 0xe4,
	0xac, 0xa4, 0x9c, 0xc4, 0x7f, 0x57, 0x6c, 0x25, 0xc9, 0x8f, 0x07, 0x07, 0xad, 0x76, 0x92, 0x56,
	0x78, 0x02, 0x83, 0x7a, 0xf8, 0xb6, 0xd7, 0xda, 0x61, 0x0a, 0x87, 0xaa, 0xca, 0xec, 0x1b, 0xeb,
	0x85, 0xfb, 0xfc, 0xc8, 0xeb, 0x7e, 0xdd, 0x18, 0xc7, 0xb0, 0x6f, 0xde, 0x59, 0x5d, 0x73, 0x41,
	0xc2, 0x8f, 0xbd, 0x74, 0x28, 0xb7, 0x1e, 0x63, 0x88, 0xf2, 0xaa, 0xa4, 0xa5, 0x7d, 0xe6, 0x0f,
	0x5a, 0x8a, 0xc0, 0x95, 0xdb, 0x11, 0x5e, 0x40, 0xe8, 0x16, 0x14, 0x61, 0xec, 0xa7, 0xd1, 0xf4,
	0xb4, 0xc1, 0x9f, 0x74, 0xa1, 0x65, 0xf3, 0x2b, 0xf9, 0xee, 0x10, 0x18, 0x85, 0x08, 0x41, 0x5e,
	0xcf, 0x6e, 0xf6, 0x77, 0xba, 0x3e, 0xd1, 0x82, 0x8c, 0xc9, 0xe6, 0xcd, 0x15, 0x86, 0x72, 0x63,
	0xfb, 0xb8, 0xfc, 0x7e, 0xae, 0x73, 0x18, 0x59, 0xb6, 0x59, 0x75, 0xf3, 0xa5, 0x58, 0xdb, 0x99,
	0x2e, 0x73, 0x72, 0x00, 0x9e, 0xdc, 0xc9, 0xa7, 0xb7, 0x10, 0xb5, 0xb6, 0xc2, 0x2b, 0x08, 0x9d,
	0xc2, 0xe3, 0x5d, 0x1c, 0x49, 0xab, 0x71, 0x5f, 0x6c, 0x54, 0xf2, 0xef, 0x75, 0xe0, 0xf2, 0xcb,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0x40, 0xd0, 0x11, 0x11, 0x02, 0x00, 0x00,
}
